[package]
name = "strings_counter"
version = "1.0.2"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Strings counter script"
homepage = "https://github.com/dinaraparanid/String-Counter"

[dependencies]
futures = "0.3.17"
async-recursion = "1.0.4"