[package]
name = "strings_counter"
version = "1.0.0"
edition = "2018"
license = "MIT/Apache-2.0"
description = "Strings counter script"
homepage = "https://github.com/dinaraparanid/String-Counter"

[dependencies]
